In [1]:
import json

from pathlib import Path

import pandas as pd
import numpy as np

import biopsykit as bp

import matplotlib.pyplot as plt

from pepbench.io import load_challenge_results_from_folder
from pepbench.io import convert_hz_to_ms
from pepbench.datasets import EmpkinsDataset, GuardianDataset

%matplotlib widget
%load_ext autoreload
%autoreload 2

In [2]:
root_path = Path("../../")

In [3]:
result_path = root_path.joinpath("results")
result_path

WindowsPath('../../results')

In [4]:
deploy_type = "local"

config_dict = json.load(root_path.joinpath("config.json").open(encoding="utf-8"))

empkins_base_path = Path(config_dict[deploy_type]["empkins_path"])
guardian_base_path = Path(config_dict[deploy_type]["guardian_path"])
print(empkins_base_path)

\Users\sebas\Development\ResearchInternship\Data\2024_08_PEP_Benchmarking\EmpkinS_Dataset

In [5]:
save_results = True

In [6]:
dataset_empkins = EmpkinsDataset(empkins_base_path, use_cache=True, only_labeled=True)
fs_empkins = dataset_empkins.sampling_rate_icg
print(f"Sampling rate ICG: {fs_empkins}")
dataset_guardian = GuardianDataset(guardian_base_path, use_cache=True, only_labeled=True)
fs_guardian = dataset_guardian.sampling_rate_icg
print(f"Sampling rate ICG: {fs_guardian}")

Sampling rate ICG: 1000
Sampling rate ICG: 500

In [7]:
algo_levels = ["q_wave_algorithm", "b_point_algorithm", "outlier_correction_algorithm"]
algo_level_mapping = dict(zip(algo_levels, ["Q-Wave Algorithm", "B-Point Algorithm", "Outlier Correction"]))

In [8]:
results_empkins = load_challenge_results_from_folder(
    result_path.joinpath("empkins_dataset_reference_q_wave").resolve(), index_cols_per_sample=["participant", "condition", "phase"]
).per_sample
results_guardian = load_challenge_results_from_folder(
    result_path.joinpath("guardian_dataset_reference_q_wave").resolve(), index_cols_per_sample=["participant", "phase"]
).per_sample

In [9]:
results_empkins = results_empkins.droplevel("condition")

In [10]:
results_empkins_norm = results_empkins.copy()
results_guardian_norm = results_guardian.copy()
results_empkins_norm[("b_point_sample", "estimated")] = results_empkins[("b_point_sample", "estimated")] - results_empkins[("heartbeat_start_sample", "estimated")]
results_empkins_norm[("b_point_sample", "reference")] = results_empkins[("b_point_sample", "reference")] - results_empkins[("heartbeat_start_sample", "estimated")]
results_guardian_norm[("b_point_sample", "estimated")] = results_guardian[("b_point_sample", "estimated")] - results_guardian[("heartbeat_start_sample", "estimated")]
results_guardian_norm[("b_point_sample", "reference")] = results_guardian[("b_point_sample", "reference")] - results_guardian[("heartbeat_start_sample", "estimated")]

In [11]:
results_guardian_norm

                                                                                                      heartbeat_id  \
                                                                                                         estimated
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0             0
                                                                                                   1             1
                                                                                                   2             2
                                                                                                   3             3
                                                                                                   4             4
...                                                                                                            ...
                 stern1985                       none                         GDN0030     TiltDown 51           51
                                                                                                   52           52
                                                                                                   53           53
                                                                                                   54           54
                                                                                                   55           55

                                                                                                                 \
                                                                                                      reference
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0          0
                                                                                                   1          1
                                                                                                   2          2
                                                                                                   3          3
                                                                                                   4          4
...                                                                                                         ...
                 stern1985                       none                         GDN0030     TiltDown 51        51
                                                                                                   52        52
                                                                                                   53        53
                                                                                                   54        54
                                                                                                   55        55

                                                                                                      heartbeat_start_sample  \
                                                                                                                   estimated
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0                     352
                                                                                                   1                     808
                                                                                                   2                    1252
                                                                                                   3                    1686
                                                                                                   4                    2116
...                                                                                                                      ...
                 stern1985                       none                         GDN0030     TiltDown 51                  27029
                                                                                                   52                  27570
                                                                                                   53                  28118
                                                                                                   54                  28652
                                                                                                   55                  29167

                                                                                                                 \
                                                                                                      reference
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0        352
                                                                                                   1        808
                                                                                                   2       1252
                                                                                                   3       1686
                                                                                                   4       2115
...                                                                                                         ...
                 stern1985                       none                         GDN0030     TiltDown 51     27029
                                                                                                   52     27570
                                                                                                   53     28118
                                                                                                   54     28652
                                                                                                   55     29167

                                                                                                      heartbeat_end_sample  \
                                                                                                                 estimated
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0                   808
                                                                                                   1                  1252
                                                                                                   2                  1686
                                                                                                   3                  2116
                                                                                                   4                  2570
...                                                                                                                    ...
                 stern1985                       none                         GDN0030     TiltDown 51                27570
                                                                                                   52                28118
                                                                                                   53                28652
                                                                                                   54                29167
                                                                                                   55                29678

                                                                                                                 \
                                                                                                      reference
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0        808
                                                                                                   1       1252
                                                                                                   2       1686
                                                                                                   3       2115
                                                                                                   4       2570
...                                                                                                         ...
                 stern1985                       none                         GDN0030     TiltDown 51     27570
                                                                                                   52     28118
                                                                                                   53     28652
                                                                                                   54     29167
                                                                                                   55     29678

                                                                                                      q_wave_onset_sample  \
                                                                                                                estimated
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0                  492
                                                                                                   1                  948
                                                                                                   2                 1386
                                                                                                   3                 1817
                                                                                                   4                 2246
...                                                                                                                   ...
                 stern1985                       none                         GDN0030     TiltDown 51               27200
                                                                                                   52               27740
                                                                                                   53               28293
                                                                                                   54               28816
                                                                                                   55               29327

                                                                                                                 \
                                                                                                      reference
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0        492
                                                                                                   1        948
                                                                                                   2       1386
                                                                                                   3       1817
                                                                                                   4       2246
...                                                                                                         ...
                 stern1985                       none                         GDN0030     TiltDown 51     27200
                                                                                                   52     27740
                                                                                                   53     28293
                                                                                                   54     28816
                                                                                                   55     29327

                                                                                                      b_point_sample  \
                                                                                                           estimated
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0           206.0
                                                                                                   1           201.0
                                                                                                   2           211.0
                                                                                                   3           214.0
                                                                                                   4           204.0
...                                                                                                              ...
                 stern1985                       none                         GDN0030     TiltDown 51          248.0
                                                                                                   52          218.0
                                                                                                   53          227.0
                                                                                                   54          194.0
                                                                                                   55          197.0

                                                                                                                 \
                                                                                                      reference
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0        216
                                                                                                   1        217
                                                                                                   2        204
                                                                                                   3        202
                                                                                                   4        177
...                                                                                                         ...
                 stern1985                       none                         GDN0030     TiltDown 51       249
                                                                                                   52       245
                                                                                                   53       227
                                                                                                   54       215
                                                                                                   55       222

                                                                                                      rr_interval_ms  \
                                                                                                           estimated
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0           912.0
                                                                                                   1           874.0
                                                                                                   2           864.0
                                                                                                   3           858.0
                                                                                                   4           936.0
...                                                                                                              ...
                 stern1985                       none                         GDN0030     TiltDown 51         1080.0
                                                                                                   52         1106.0
                                                                                                   53         1046.0
                                                                                                   54         1022.0
                                                                                                   55            NaN

                                                                                                      pep_sample  \
                                                                                                       estimated
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0        66.0
                                                                                                   1        61.0
                                                                                                   2        77.0
                                                                                                   3        83.0
                                                                                                   4        74.0
...                                                                                                          ...
                 stern1985                       none                         GDN0030     TiltDown 51       77.0
                                                                                                   52       48.0
                                                                                                   53       52.0
                                                                                                   54       30.0
                                                                                                   55       37.0

                                                                                                                 \
                                                                                                      reference
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0         76
                                                                                                   1         77
                                                                                                   2         70

In [12]:
#results_empkins_cleaned = results_empkins_norm.dropna(subset=[("b_point_sample", "estimated")])
#results_guardian_cleaned = results_guardian_norm.dropna(subset=[("b_point_sample", "estimated")])
results_empkins_cleaned = results_empkins_norm
results_guardian_cleaned = results_guardian_norm

In [13]:
cols = [("heartbeat_start_sample", "estimated"), ("heartbeat_start_sample", "reference"), ("heartbeat_end_sample", "estimated"), ("heartbeat_end_sample", "reference"), ("q_wave_onset_sample", "estimated"), ("q_wave_onset_sample", "reference"), ("b_point_sample", "estimated"), ("b_point_sample", "reference"), ("pep_sample", "estimated"), ("pep_sample", "reference")]
results_empkins_cleaned_ms = results_empkins_cleaned.copy()
results_guardian_cleaned_ms = results_guardian_cleaned.copy()
results_empkins_cleaned_ms[cols] = results_empkins_cleaned[cols] * convert_hz_to_ms(sampling_frequency=fs_empkins)
results_guardian_cleaned_ms[cols] = results_guardian_cleaned[cols] * convert_hz_to_ms(sampling_frequency=fs_guardian)

In [14]:
results_guardian_cleaned_ms

                                                                                                      heartbeat_id  \
                                                                                                         estimated
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0             0
                                                                                                   1             1
                                                                                                   2             2
                                                                                                   3             3
                                                                                                   4             4
...                                                                                                            ...
                 stern1985                       none                         GDN0030     TiltDown 51           51
                                                                                                   52           52
                                                                                                   53           53
                                                                                                   54           54
                                                                                                   55           55

                                                                                                                 \
                                                                                                      reference
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0          0
                                                                                                   1          1
                                                                                                   2          2
                                                                                                   3          3
                                                                                                   4          4
...                                                                                                         ...
                 stern1985                       none                         GDN0030     TiltDown 51        51
                                                                                                   52        52
                                                                                                   53        53
                                                                                                   54        54
                                                                                                   55        55

                                                                                                      heartbeat_start_sample  \
                                                                                                                   estimated
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0                   704.0
                                                                                                   1                  1616.0
                                                                                                   2                  2504.0
                                                                                                   3                  3372.0
                                                                                                   4                  4232.0
...                                                                                                                      ...
                 stern1985                       none                         GDN0030     TiltDown 51                54058.0
                                                                                                   52                55140.0
                                                                                                   53                56236.0
                                                                                                   54                57304.0
                                                                                                   55                58334.0

                                                                                                                 \
                                                                                                      reference
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0      704.0
                                                                                                   1     1616.0
                                                                                                   2     2504.0
                                                                                                   3     3372.0
                                                                                                   4     4230.0
...                                                                                                         ...
                 stern1985                       none                         GDN0030     TiltDown 51   54058.0
                                                                                                   52   55140.0
                                                                                                   53   56236.0
                                                                                                   54   57304.0
                                                                                                   55   58334.0

                                                                                                      heartbeat_end_sample  \
                                                                                                                 estimated
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0                1616.0
                                                                                                   1                2504.0
                                                                                                   2                3372.0
                                                                                                   3                4232.0
                                                                                                   4                5140.0
...                                                                                                                    ...
                 stern1985                       none                         GDN0030     TiltDown 51              55140.0
                                                                                                   52              56236.0
                                                                                                   53              57304.0
                                                                                                   54              58334.0
                                                                                                   55              59356.0

                                                                                                                 \
                                                                                                      reference
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0     1616.0
                                                                                                   1     2504.0
                                                                                                   2     3372.0
                                                                                                   3     4230.0
                                                                                                   4     5140.0
...                                                                                                         ...
                 stern1985                       none                         GDN0030     TiltDown 51   55140.0
                                                                                                   52   56236.0
                                                                                                   53   57304.0
                                                                                                   54   58334.0
                                                                                                   55   59356.0

                                                                                                      q_wave_onset_sample  \
                                                                                                                estimated
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0                984.0
                                                                                                   1               1896.0
                                                                                                   2               2772.0
                                                                                                   3               3634.0
                                                                                                   4               4492.0
...                                                                                                                   ...
                 stern1985                       none                         GDN0030     TiltDown 51             54400.0
                                                                                                   52             55480.0
                                                                                                   53             56586.0
                                                                                                   54             57632.0
                                                                                                   55             58654.0

                                                                                                                 \
                                                                                                      reference
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0      984.0
                                                                                                   1     1896.0
                                                                                                   2     2772.0
                                                                                                   3     3634.0
                                                                                                   4     4492.0
...                                                                                                         ...
                 stern1985                       none                         GDN0030     TiltDown 51   54400.0
                                                                                                   52   55480.0
                                                                                                   53   56586.0
                                                                                                   54   57632.0
                                                                                                   55   58654.0

                                                                                                      b_point_sample  \
                                                                                                           estimated
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0           412.0
                                                                                                   1           402.0
                                                                                                   2           422.0
                                                                                                   3           428.0
                                                                                                   4           408.0
...                                                                                                              ...
                 stern1985                       none                         GDN0030     TiltDown 51          496.0
                                                                                                   52          436.0
                                                                                                   53          454.0
                                                                                                   54          388.0
                                                                                                   55          394.0

                                                                                                                 \
                                                                                                      reference
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0      432.0
                                                                                                   1      434.0
                                                                                                   2      408.0
                                                                                                   3      404.0
                                                                                                   4      354.0
...                                                                                                         ...
                 stern1985                       none                         GDN0030     TiltDown 51     498.0
                                                                                                   52     490.0
                                                                                                   53     454.0
                                                                                                   54     430.0
                                                                                                   55     444.0

                                                                                                      rr_interval_ms  \
                                                                                                           estimated
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0           912.0
                                                                                                   1           874.0
                                                                                                   2           864.0
                                                                                                   3           858.0
                                                                                                   4           936.0
...                                                                                                              ...
                 stern1985                       none                         GDN0030     TiltDown 51         1080.0
                                                                                                   52         1106.0
                                                                                                   53         1046.0
                                                                                                   54         1022.0
                                                                                                   55            NaN

                                                                                                      pep_sample  \
                                                                                                       estimated
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0       132.0
                                                                                                   1       122.0
                                                                                                   2       154.0
                                                                                                   3       166.0
                                                                                                   4       148.0
...                                                                                                          ...
                 stern1985                       none                         GDN0030     TiltDown 51      154.0
                                                                                                   52       96.0
                                                                                                   53      104.0
                                                                                                   54       60.0
                                                                                                   55       74.0

                                                                                                                 \
                                                                                                      reference
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              GDN0005     Pause    0      152.0
                                                                                                   1      154.0
                                                                                                   2      140.0

In [15]:
preprocessed_results_empkins_guardian = pd.concat([results_empkins_cleaned_ms, results_guardian_cleaned_ms])
preprocessed_results_empkins_guardian

                                                                                                      heartbeat_id  \
                                                                                                         estimated
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              VP_001      Prep     0             0
                                                                                                   1             1
                                                                                                   2             2
                                                                                                   3             3
                                                                                                   4             4
...                                                                                                            ...
                 stern1985                       none                         GDN0030     TiltDown 51           51
                                                                                                   52           52
                                                                                                   53           53
                                                                                                   54           54
                                                                                                   55           55

                                                                                                                 \
                                                                                                      reference
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              VP_001      Prep     0          0
                                                                                                   1          1
                                                                                                   2          2
                                                                                                   3          3
                                                                                                   4          4
...                                                                                                         ...
                 stern1985                       none                         GDN0030     TiltDown 51        51
                                                                                                   52        52
                                                                                                   53        53
                                                                                                   54        54
                                                                                                   55        55

                                                                                                      heartbeat_start_sample  \
                                                                                                                   estimated
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              VP_001      Prep     0                   394.0
                                                                                                   1                   984.0
                                                                                                   2                  1569.0
                                                                                                   3                  2134.0
                                                                                                   4                  2684.0
...                                                                                                                      ...
                 stern1985                       none                         GDN0030     TiltDown 51                54058.0
                                                                                                   52                55140.0
                                                                                                   53                56236.0
                                                                                                   54                57304.0
                                                                                                   55                58334.0

                                                                                                                 \
                                                                                                      reference
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              VP_001      Prep     0      399.0
                                                                                                   1      985.0
                                                                                                   2     1569.0
                                                                                                   3     2134.0
                                                                                                   4     2684.0
...                                                                                                         ...
                 stern1985                       none                         GDN0030     TiltDown 51   54058.0
                                                                                                   52   55140.0
                                                                                                   53   56236.0
                                                                                                   54   57304.0
                                                                                                   55   58334.0

                                                                                                      heartbeat_end_sample  \
                                                                                                                 estimated
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              VP_001      Prep     0                 984.0
                                                                                                   1                1569.0
                                                                                                   2                2134.0
                                                                                                   3                2684.0
                                                                                                   4                3227.0
...                                                                                                                    ...
                 stern1985                       none                         GDN0030     TiltDown 51              55140.0
                                                                                                   52              56236.0
                                                                                                   53              57304.0
                                                                                                   54              58334.0
                                                                                                   55              59356.0

                                                                                                                 \
                                                                                                      reference
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              VP_001      Prep     0      985.0
                                                                                                   1     1569.0
                                                                                                   2     2134.0
                                                                                                   3     2684.0
                                                                                                   4     3227.0
...                                                                                                         ...
                 stern1985                       none                         GDN0030     TiltDown 51   55140.0
                                                                                                   52   56236.0
                                                                                                   53   57304.0
                                                                                                   54   58334.0
                                                                                                   55   59356.0

                                                                                                      q_wave_onset_sample  \
                                                                                                                estimated
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              VP_001      Prep     0                567.0
                                                                                                   1               1156.0
                                                                                                   2               1735.0
                                                                                                   3               2291.0
                                                                                                   4               2846.0
...                                                                                                                   ...
                 stern1985                       none                         GDN0030     TiltDown 51             54400.0
                                                                                                   52             55480.0
                                                                                                   53             56586.0
                                                                                                   54             57632.0
                                                                                                   55             58654.0

                                                                                                                 \
                                                                                                      reference
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              VP_001      Prep     0      567.0
                                                                                                   1     1156.0
                                                                                                   2     1735.0
                                                                                                   3     2291.0
                                                                                                   4     2846.0
...                                                                                                         ...
                 stern1985                       none                         GDN0030     TiltDown 51   54400.0
                                                                                                   52   55480.0
                                                                                                   53   56586.0
                                                                                                   54   57632.0
                                                                                                   55   58654.0

                                                                                                      b_point_sample  \
                                                                                                           estimated
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              VP_001      Prep     0           275.0
                                                                                                   1           254.0
                                                                                                   2           265.0
                                                                                                   3           260.0
                                                                                                   4           259.0
...                                                                                                              ...
                 stern1985                       none                         GDN0030     TiltDown 51          496.0
                                                                                                   52          436.0
                                                                                                   53          454.0
                                                                                                   54          388.0
                                                                                                   55          394.0

                                                                                                                 \
                                                                                                      reference
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              VP_001      Prep     0      240.0
                                                                                                   1      222.0
                                                                                                   2      242.0
                                                                                                   3      248.0
                                                                                                   4      242.0
...                                                                                                         ...
                 stern1985                       none                         GDN0030     TiltDown 51     498.0
                                                                                                   52     490.0
                                                                                                   53     454.0
                                                                                                   54     430.0
                                                                                                   55     444.0

                                                                                                      rr_interval_ms  \
                                                                                                           estimated
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              VP_001      Prep     0           590.0
                                                                                                   1           581.0
                                                                                                   2           557.0
                                                                                                   3           546.0
                                                                                                   4           541.0
...                                                                                                              ...
                 stern1985                       none                         GDN0030     TiltDown 51         1080.0
                                                                                                   52         1106.0
                                                                                                   53         1046.0
                                                                                                   54         1022.0
                                                                                                   55            NaN

                                                                                                      pep_sample  \
                                                                                                       estimated
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              VP_001      Prep     0       102.0
                                                                                                   1        82.0
                                                                                                   2        99.0
                                                                                                   3       103.0
                                                                                                   4        97.0
...                                                                                                          ...
                 stern1985                       none                         GDN0030     TiltDown 51      154.0
                                                                                                   52       96.0
                                                                                                   53      104.0
                                                                                                   54       60.0
                                                                                                   55       74.0

                                                                                                                 \
                                                                                                      reference
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              VP_001      Prep     0       67.0
                                                                                                   1       50.0
                                                                                                   2       76.0

In [16]:
print(preprocessed_results_empkins_guardian.shape[0] - (results_empkins_cleaned_ms.shape[0] + results_guardian_cleaned_ms.shape[0]))

0

In [18]:
input_data = preprocessed_results_empkins_guardian

In [19]:
input_data = input_data[[("heartbeat_id", "reference"), ("b_point_sample", "estimated"), ("b_point_sample", "reference")]]
input_data.columns = input_data.columns.to_flat_index().str.join("_")
input_data.droplevel("q_wave_algorithm")
input_data

                                                                                                       heartbeat_id_reference  \
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              VP_001      Prep     0                        0
                                                                                                   1                        1
                                                                                                   2                        2
                                                                                                   3                        3
                                                                                                   4                        4
...                                                                                                                       ...
                 stern1985                       none                         GDN0030     TiltDown 51                      51
                                                                                                   52                      52
                                                                                                   53                      53
                                                                                                   54                      54
                                                                                                   55                      55

                                                                                                       b_point_sample_estimated  \
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              VP_001      Prep     0                      275.0
                                                                                                   1                      254.0
                                                                                                   2                      265.0
                                                                                                   3                      260.0
                                                                                                   4                      259.0
...                                                                                                                         ...
                 stern1985                       none                         GDN0030     TiltDown 51                     496.0
                                                                                                   52                     436.0
                                                                                                   53                     454.0
                                                                                                   54                     388.0
                                                                                                   55                     394.0

                                                                                                       b_point_sample_reference
q_wave_algorithm b_point_algorithm               outlier_correction_algorithm participant phase
q-wave-reference arbol2017-isoelectric-crossings forouzanfar2018              VP_001      Prep     0                      240.0
                                                                                                   1                      222.0
                                                                                                   2                      242.0
                                                                                                   3                      248.0
                                                                                                   4                      242.0
...                                                                                                                         ...
                 stern1985                       none                         GDN0030     TiltDown 51                     498.0
                                                                                                   52                     490.0
                                                                                                   53                     454.0
                                                                                                   54                     430.0
                                                                                                   55                     444.0

[348330 rows x 3 columns]

In [20]:
input_data["algo_combis"] = input_data.index.get_level_values("b_point_algorithm") + "_" + input_data.index.get_level_values("outlier_correction_algorithm")
input_data = input_data.reset_index().drop(columns=["b_point_algorithm", "outlier_correction_algorithm"])
input_data

C:\Users\sebas\AppData\Local\Temp\ipykernel_47796\3413036251.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  input_data["algo_combis"] = input_data.index.get_level_values("b_point_algorithm") + "_" + input_data.index.get_level_values("outlier_correction_algorithm")

,q_wave_algorithm,participant,phase,level_5,heartbeat_id_reference,b_point_sample_estimated,b_point_sample_reference,algo_combis
0,q-wave-reference,VP_001,Prep,0,0,275.0,240.0,arbol2017-isoelectric-crossings_forouzanfar2018
1,q-wave-reference,VP_001,Prep,1,1,254.0,222.0,arbol2017-isoelectric-crossings_forouzanfar2018
2,q-wave-reference,VP_001,Prep,2,2,265.0,242.0,arbol2017-isoelectric-crossings_forouzanfar2018
3,q-wave-reference,VP_001,Prep,3,3,260.0,248.0,arbol2017-isoelectric-crossings_forouzanfar2018
4,q-wave-reference,VP_001,Prep,4,4,259.0,242.0,arbol2017-isoelectric-crossings_forouzanfar2018
...,...,...,...,...,...,...,...,...
348325,q-wave-reference,GDN0030,TiltDown,51,51,496.0,498.0,stern1985_none
348326,q-wave-reference,GDN0030,TiltDown,52,52,436.0,490.0,stern1985_none
348327,q-wave-reference,GDN0030,TiltDown,53,53,454.0,454.0,stern1985_none
348328,q-wave-reference,GDN0030,TiltDown,54,54,388.0,430.0,stern1985_none
348329,q-wave-reference,GDN0030,TiltDown,55,55,394.0,444.0,stern1985_none

In [21]:
# Pivot the DataFrame
input_data_wide = input_data.pivot_table(
    index=['participant', 'phase', 'heartbeat_id_reference', 'b_point_sample_reference'],
    columns="algo_combis",
    values='b_point_sample_estimated'
).reset_index()

# Flatten the columns
input_data_wide.columns.name = None
input_data_wide.columns = [f'{col}' if isinstance(col, str) else f'{col[1]}' for col in input_data_wide.columns]
input_data_wide

,participant,phase,heartbeat_id_reference,b_point_sample_reference,arbol2017-isoelectric-crossings_forouzanfar2018,arbol2017-isoelectric-crossings_linear-interpolation,arbol2017-isoelectric-crossings_none,arbol2017-second-derivative_forouzanfar2018,arbol2017-second-derivative_linear-interpolation,arbol2017-second-derivative_none,...,lozano2007-linear-regression_none,lozano2007-quadratic-regression_forouzanfar2018,lozano2007-quadratic-regression_linear-interpolation,lozano2007-quadratic-regression_none,sherwood1990_forouzanfar2018,sherwood1990_linear-interpolation,sherwood1990_none,stern1985_forouzanfar2018,stern1985_linear-interpolation,stern1985_none
0,GDN0005,HoldingBreath,0,388.0,438.0,438.0,438.0,398.0,398.0,398.0,...,412.0,384.0,384.0,384.0,442.0,442.0,442.0,388.0,388.0,388.0
1,GDN0005,HoldingBreath,1,404.0,420.0,422.0,340.0,350.0,350.0,350.0,...,404.0,384.0,384.0,384.0,422.0,420.0,330.0,402.0,402.0,402.0
2,GDN0005,HoldingBreath,3,376.0,382.0,382.0,382.0,296.0,296.0,296.0,...,366.0,348.0,348.0,348.0,382.0,382.0,382.0,374.0,374.0,374.0
3,GDN0005,HoldingBreath,4,390.0,394.0,394.0,394.0,344.0,344.0,344.0,...,372.0,354.0,358.0,348.0,394.0,394.0,394.0,388.0,388.0,388.0
4,GDN0005,HoldingBreath,5,386.0,398.0,398.0,398.0,312.0,312.0,312.0,...,378.0,360.0,366.0,354.0,400.0,400.0,400.0,384.0,384.0,384.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11219,VP_032,Talk,39,310.0,335.0,335.0,335.0,276.0,276.0,276.0,...,305.0,294.0,294.0,294.0,337.0,337.0,337.0,306.0,306.0,306.0
11220,VP_032,Talk,40,322.0,331.0,331.0,331.0,298.0,298.0,298.0,...,321.0,316.0,317.0,303.0,329.0,329.0,329.0,287.0,287.0,287.0
11221,VP_032,Talk,41,340.0,317.0,317.0,317.0,300.0,300.0,300.0,...,332.0,322.0,322.0,322.0,311.0,311.0,311.0,287.0,287.0,287.0
11222,VP_032,Talk,42,311.0,365.0,365.0,365.0,324.0,324.0,324.0,...,351.0,337.0,337.0,337.0,368.0,368.0,368.0,305.0,305.0,305.0
11223,VP_032,Talk,43,307.0,342.0,342.0,342.0,313.0,313.0,313.0,...,341.0,329.0,329.0,329.0,334.0,334.0,334.0,301.0,301.0,301.0

In [22]:
input_data_wide = input_data_wide.dropna()
input_data_wide

,participant,phase,heartbeat_id_reference,b_point_sample_reference,arbol2017-isoelectric-crossings_forouzanfar2018,arbol2017-isoelectric-crossings_linear-interpolation,arbol2017-isoelectric-crossings_none,arbol2017-second-derivative_forouzanfar2018,arbol2017-second-derivative_linear-interpolation,arbol2017-second-derivative_none,...,lozano2007-linear-regression_none,lozano2007-quadratic-regression_forouzanfar2018,lozano2007-quadratic-regression_linear-interpolation,lozano2007-quadratic-regression_none,sherwood1990_forouzanfar2018,sherwood1990_linear-interpolation,sherwood1990_none,stern1985_forouzanfar2018,stern1985_linear-interpolation,stern1985_none
0,GDN0005,HoldingBreath,0,388.0,438.0,438.0,438.0,398.0,398.0,398.0,...,412.0,384.0,384.0,384.0,442.0,442.0,442.0,388.0,388.0,388.0
1,GDN0005,HoldingBreath,1,404.0,420.0,422.0,340.0,350.0,350.0,350.0,...,404.0,384.0,384.0,384.0,422.0,420.0,330.0,402.0,402.0,402.0
2,GDN0005,HoldingBreath,3,376.0,382.0,382.0,382.0,296.0,296.0,296.0,...,366.0,348.0,348.0,348.0,382.0,382.0,382.0,374.0,374.0,374.0
3,GDN0005,HoldingBreath,4,390.0,394.0,394.0,394.0,344.0,344.0,344.0,...,372.0,354.0,358.0,348.0,394.0,394.0,394.0,388.0,388.0,388.0
4,GDN0005,HoldingBreath,5,386.0,398.0,398.0,398.0,312.0,312.0,312.0,...,378.0,360.0,366.0,354.0,400.0,400.0,400.0,384.0,384.0,384.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11219,VP_032,Talk,39,310.0,335.0,335.0,335.0,276.0,276.0,276.0,...,305.0,294.0,294.0,294.0,337.0,337.0,337.0,306.0,306.0,306.0
11220,VP_032,Talk,40,322.0,331.0,331.0,331.0,298.0,298.0,298.0,...,321.0,316.0,317.0,303.0,329.0,329.0,329.0,287.0,287.0,287.0
11221,VP_032,Talk,41,340.0,317.0,317.0,317.0,300.0,300.0,300.0,...,332.0,322.0,322.0,322.0,311.0,311.0,311.0,287.0,287.0,287.0
11222,VP_032,Talk,42,311.0,365.0,365.0,365.0,324.0,324.0,324.0,...,351.0,337.0,337.0,337.0,368.0,368.0,368.0,305.0,305.0,305.0
11223,VP_032,Talk,43,307.0,342.0,342.0,342.0,313.0,313.0,313.0,...,341.0,329.0,329.0,329.0,334.0,334.0,334.0,301.0,301.0,301.0

In [24]:
if save_results:
    input_data_wide.to_csv(result_path.joinpath("data/train_data.csv"))